curl/project/config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'

  devise_for :users
  get 'static_pages/home'
  get 'static_pages/lod'
  get 'static_pages/zasady'
  get 'static_pages/sprzet'
  get 'static_pages/fizyka'
  get 'static_pages/kontakt'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :categories
  resources :words

  get 'search', to: 'search#search'

    resources :words do
      collection { get :search }
    end

  get "*any", via: :all, to: "errors#not_found"
end

curl/project/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, :all if user.admin?
  end
end

curl/project/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

curl/project/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words

end

curl/project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin
  end
end

curl/project/app/models/word.rb
class Word < ActiveRecord::Base

  belongs_to :category
  before_create :check_translation
  before_update :track_changes

   validates :name, presence: true, uniqueness: true, allow_blank: false

  def self.search(query)
      if query
          where("name like ?", "%#{query}%")
      else
          all
      end
  end

  def check_translation
    self.displayed = translation.present? ? false : true
    self
  end

  def track_changes
    TranslationMailer.notification_email(mail).deliver_now if (self.displayed_changed? && self.displayed == false)
    self
  end

  def check_translation
    self.displayed = translation.present? ? false : true
    self
  end

end

curl/project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied, with: :not_authorized

  private

  def not_authorized
    redirect_to root_url, alert: "Unauthorized Access"
  end
end

curl/project/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  authorize_resource only: [:update, :delete]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

curl/project/app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

curl/project/app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check
  def search
    if params[:q].nil?
      @words = []
    else
      @words = Word.search params[:q]
    end
  end

end

curl/project/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_authorization_check

  def home
  end
  def fizyka
  end
  def kontakt
  end
  def lod
  end
  def zasady
  end
  def sprzet
  end
end

curl/project/app/controllers/words_controller.rb
class WordsController < ApplicationController
    skip_authorization_check
  #before_action :set_word, only: [:show, :edit, :update, :destroy]
  def index
    @words = Word.search(params[:q])
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def edit
    @word = Word.find(params[:id])
  end

  def create
    @word = Word.new(word_params)
    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @word = Word.find(params[:id])
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def word_params
    params.require(:word).permit(:name, :translation, :displayed, :mail)
  end

  def set_word
    @word = Word.find(params[:id])
  end

end

curl/project/app/helpers/application_helper.rb
module ApplicationHelper
end

curl/project/app/helpers/categories_helper.rb
module CategoriesHelper
end

curl/project/app/helpers/search_helper.rb
module SearchHelper
end

curl/project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

curl/project/app/helpers/words_helper.rb
module WordsHelper
  #def devise_error_messages!
     #resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  #end
end

curl/project/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

curl/project/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

curl/project/app/views/categories/index.html.erb
<div class="main">
<p id="notice"><%= notice %></p>

<h1>Słownik terminów curlingowych został podzielony na następujące kategorie:</h1>

  <% @categories.each do |category| %>
        <strong><%= link_to category.name, category %></strong><br><br>
  <% end %>

  <p><%= link_to 'Wszystkie słowa', words_path %></p>

</div>

curl/project/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

curl/project/app/views/categories/show.html.erb
<div class="main">
<p id="notice"><%= notice %></p>

Słowa z kategorii: <strong><%= @category.name %></strong>
</p>
<% if @category.words.count > 0 %>
    <table>
      <% @category.words.each do |attr| %>
          <tbody>
          <tr>
            <td> <strong><%= attr.name %></strong></td>
            <td><%= attr.translation %></td>
          </tr>
          </tbody>
      <% end %>
    </table>
<% else %>
    <div>
      <p>Ta kategoria nie ma jeszcze żadnych słów.</p>
    </div>
<% end %>
  <br><br>
  <p>
    <%= link_to 'Lista wszystkich kategorii', categories_path %><br><br>
    <%= link_to 'Lista wszystkich słów w słowniku', words_path %><br><br>
  </p>
</div>

curl/project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Przepis na curling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <title>Przepis na curling</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-2" />
  <meta name=viewport" content="width=device-width, initial-scale=1.0" />

  <script src="http://codepen.io/username/pen/aBcDef"></script>

</head>
<body>

<header>
  <h1>Przepis na curling</h1>
  <h3>Wszystko, czego nie wiesz o tym sporcie</h3>
</header>
<nav class="main-nav">
  <%= link_to "Duch curlingu", static_pages_home_path %>
      <%= link_to "Tor do gry", static_pages_lod_path %>
      <%= link_to "Zasady", static_pages_zasady_path %>
      <%= link_to "Sprzęt do gry", static_pages_sprzet_path %>
      <%= link_to "Fizyka curlingu", static_pages_fizyka_path %>
      <%= link_to "Słownik", categories_path %>
      <%= link_to "Kontakt", static_pages_kontakt_path %>
  </nav>

<%= yield %>


</body>
</html>

curl/project/app/views/search/search.erb
<h1>Words Search</h1>
<%= form_for search_path, method: :get do |f| %>
    <p>
      <%= f.label "Search for" %>
      <%= text_field_tag :q, params[:q] %>
      <%= submit_tag "Go", name: nil %>
    </p>
<% end %>
<ul>
  <% @words.each do |word| %>
      <li>
        <h3>
          <%= link_to word.try(:highlight).try(:name) ? word.highlight.name[0].html_safe : word.name,
                      controller: "words",
                      action: "show",
                      id: word.id%>
        </h3>
      </li>
  <% end %>
</ul>

curl/project/app/views/static_pages/fizyka.html.erb
<div class="main">
<p>
	<h1>Dlaczego kamień skręca - teoria 1</h1>
Gdy kamień ślizga się po lodzie, chropowata, przednia połowa powierzchni kamienia sprawia, że powstają niewielkie zarysowania na lodzie. Obrót kamienia daje rysom nieznaczne odchylenie od kierunku, w którym kręci się kamień. Gdy chropowata, tylna połowa kamienia przejeżdża przez ten sam obszar lodu, pokonuje wcześniejsze zarysowania pod niewielkim kątem. Podczas tej czynności występuje w tylnej części kamienia tendencja do poruszania się wzdłuż pokonywanych rys. Jest to właśnie "kierowanie przez zarysowania" lub inaczej mówiąc, mechanizm sterowania torem ślizgu, który to mechanizm wytwarza boczną siłę, niezbędną do spowodowania skrętu.
</p>
</div>

curl/project/app/views/static_pages/home.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
</head>
<body>

<div class="main">

<div class="article">
  <h2>Duch curlingu</h2>
  <p>Przez ponad 500 lat istota curlingu bazowała na przestrzeganiu reguł, szacunku do przeciwnika i przekonaniu, że czerpanie przyjemności z gry jest ważniejsze niż wygrywanie. Curling jest grą z długą tradycją. Prawdziwy curler zawsze przestrzega ducha tej gry. Zawodnicy nie łamią zasad specjalnie, wolą raczej przegrać, niż wygrać nieuczciwie. Curler nigdy nie przeszkadza innym podczas zagrań, a podczas gry zawsze pierwszy przyznaje się do swojego błędu. Duch curlingu wymaga zachowania sportowej postawy i życzliwego, honorowego zachowania. Duch curling wpływa zarówno na interpretację zasad i reguł gry, jak i na zachowanie curlerów na lodzie i poza nim.
</p>
</div>

</div>
</body>
</html>

curl/project/app/views/static_pages/kontakt.html.erb
<div class="main">

<div class="article">
	<p> Strona wykonana jako projekt licencja
	</p>
  <h2>Napisz maila: admin@example.com</h2>

  <h3>Kluby curlingowe w Polsce, będące członkami<a href="http://http://pfkc.pl"><strong><br>Polskiej Federacji Klubów Curlingowych</strong> </a></h3>
  <a href="http://www.kkc-curling.pl/"><strong>Krakowski Klub Curlingowy</strong> </a><br>
  <a href="http://www.skc.katowice.pl/"><strong>Śląski Klub Curlingowy</strong> </a><br>
  <a href="http://mccwarszawa.pl/"><strong>Media Curling Clumb - Warszawa</strong> </a><br>
  <a href="http://culani.org.pl/"><strong>ISRS Culani - curling na wózkach</strong> </a><br>
  <a href="http://www.sopot.curling.pl/"><strong>Sopot Curling Club Wa ku'ta</strong> </a><br>
  <a href="http://azs.gliwice.pl/"><strong>AZS Politechnika Śląska Gliwice</strong> </a><br>
  <a href="http://www.pos.org.pl/index.php/sekcje/curling"><strong>Polska Organizacja Sportowa - curling w Łodzi</strong> </a><br>
  <a href="http://poznan.curling.pl/"><strong>Poznański Klub Curlingowy</strong> </a><br>
  <a href="http://bkc.curling.net.pl/"><strong>Bełchatowski Klub Curlingowy</strong> </a><br>
  <a href="http://www.curlingpaw.dbv.pl/news.php"><strong>Klub Curlingowy KS Warszowice</strong> </a><br>
  </p>
  <br>
  <br>

  <p>
  	<a href="http://www.curlingcalendar.com/"><strong>Kalendarz turniejów curlingowych na świecie</strong> </a><br>

  </p>

</div>

</div>

curl/project/app/views/static_pages/lod.html.erb
<div class="main">

  <h1>Przygotowanie lodu</h1>
  <%= image_tag('tor_caly.png', size: "200x850", alt: "tor curlingowy") %>
  <p>W curling gra się na lodzie. Jest to ten sam lód, który używają hokeiści, łyżwiarze. Jednak w curlingu lód musi spełniać pewne wymogi, ponieważ źle przygotowany jest najgorszym koszmarem curlera. Za przygotowanie lodu odpowiedzialna jest osoba zwana ice masterem. Jest to czynność wymagająca doświadczenia i umiejętności.
</p>
  <p>Lód do gry w curling powinien być płaską powierzchnią bez żadnych zarysowań, czy wgłębień. Zanim zacznie się proces przygotowywania lodu do gry, jest on czyszczony ze wszelkich zanieczyszczeń. Po uzyskaniu równej powierzchni ice master spryskuje ją małymi kropelkami wody tworząc warstwę pebbli. Odbywa się to za pomocą zbiornika z wodą i przymocowaną do niego specjalną rączką z otworami podobnymi do dziurek w prysznicu. Ice master przechodzi kilka razy wzdłuż toru dokładnie pokrywając lód kropelkami wody. Najlepsza do tego celu jest woda ciepła, ponieważ szybciej zamarza niż woda zimna. Po około 30 sekundach zamarznięte kropelki tworzą pebblę.
</p>
<p>
<%= image_tag('tor_opisy.png', size: "680x875", alt: "tor curlingowy opisy linii") %>
</p>
  <p>Po zrobieniu pebbli następuje ścięcie najwyższych wystających górek lodu powstałych z zamarzających kropelek.  Ice master może użyć w tym celu maszyny z przymocowanym ostrzem, które ścina określoną wysokość lodu (same szczyty pebbli). Innym sposobem jest przejechanie po całym torze kilkoma kamieniami używając specjalnego przyrządu, co powoduje wygładzenie najbardziej wystających zamarzniętych kropelek.
</p>
  <p>Zdarza się, że niewielkie kryształki lodu przyczepiają się do powierzchni kamienia. Może to spowodować znaczącą zmianę toru poruszania się – zmianę rotacji lub nawet zatrzymanie się kamienia.
</p>
</div>

curl/project/app/views/static_pages/sprzet.html.erb
<div class="main">
  <div class="article">
    <h1>Buty</h1>
    <p>
      <%= image_tag('buty.jpg', size: "300x300", alt: "buty do curlingu") %>
      Podczas gry zawodnicy muszą nosić specjalnie przygotowane obuwie. Podeszwa jednego z butów jest pokryta cienką
      warstwą teflonu bądź innego tworzywa o gładkiej powierzchni. Aby zaoszczędzić, istnieje możliwość zakupu podkładki
      teflonowej, którą można przymocować do dowolnego obuwia za pomocą elastycznych gumek. Dzięki temu curlerzy mogą
      ślizgać się przy startowaniu z haka. Leworęczni zawodnicy śliską podeszwę noszą na prawym bucie, a praworęczni –
      na lewym. Spód drugiego buta jest pokryty cienką warstwą gumy, aby zwiększyć przyczepność. Oprócz tego używa się
      nakładki na but o gładkiej powierzchni, aby zawodnik mógł zachować równowagę na lodzie.
    </p>
  </div>
  <div class="article">
    <h1>Szczotka</h1>
    <p>
      <%= image_tag('broom.jpg', size: "300x300", alt: "szczotka do curlingu") %>
      Szczotek w curlingu używa się do szczotkowania lodu. Dodatkowo skip używa ich do wskazywania swoim zawodnikom
      miejsca, w które mają celować. Innym zastosowaniem tego przyrządu jest trzymanie go podczas wypuszczania kamienia,
      aby łatwiej było zachować równowagę.
    </p>
  </div>
  <div class="article">
    <h1>Kamień</h1>
    <p>
      <%= image_tag('kamien1.jpg', size: "300x300", alt: "kamień curlingowy") %>
      Kamienie curlingowe mają okrągły kształt i ważą 19,96 kg. Każda drużyna podczas gry używa zestawu 8 kamieni o tym
      samym kolorze lub oznaczeniu. Do kamienia jest przymocowana specjalna rączka, dzięki której można nadać mu
      odpowiednią rotację. Kamienie do gry sa wykonane ze specjalnego granitu, który nie pochłania wody.
    </p>
  </div>
  <div class="article">
    <h1>Ekstender</h1>
    <p>
      <%= image_tag('stick.jpg', size: "300x300", alt: "ekstender do curlingu na wózkach") %>
      Jest to przyrząd, który służy do wypuszczania kamieni przez osoby grające na wózkach. Za jego pomocą mogą oni
      nadać kamieniowi siłę i rotację bez konieczności ślizgania się po lodzie. W curlingu na wózkach używa się ekstenderów
      zamiast szczotek (nie szczotkuje się lodu).
    </p>
  </div>

</div>

curl/project/app/views/static_pages/zasady.html.erb
<div class="main">
<div class="article">
  <h1>Rzucanie kamieni</h1>
  <p>
  W czasie jednego enda drużyny wykonują rzuty kamieniami na przemian, przy czym każdy z uczestników meczu wypuszcza po dwa kamienie. Zawodnicy wypuszczają kamienie w określonej kolejności przez cały mecz. Osoba zagrywająca nadaje kamieniowi odpowiednią prędkość, rotację oraz kierunek. Już po jego wypuszczeniu istnieje możliwość korygowania toru po jakim się on porusza poprzez szczotkowanie powierzchni przed nim. Kiedy już wszystkie kamienie zostaną wykorzystane, oblicza się liczbę zdobytych punktów i rozpoczyna kolejny end z drugiego końca toru. Każdy mecz trwa od 6 do 10 endów.
  <p>
</div>

    <div class="article">
  <h1>Kto co robi w trakcie rzutu?</h1>
  <p>
  <%= image_tag('rzut.jpg', size: "420x320", alt: "zawodnicy podczas zagrania") %>
  Drużyna curlingowa składa się z czterech osób: pierwszy (lead), drugi, trzeci (wiceskip), czwarty (skip). Skip jest najważniejszym zawodnikiem, ponieważ to on decyduje o taktyce drużyny. Jako jedyny może przebywać w obrębie domu, a także szczotkować kamienie przeciwnika. W czasie, gdy skip wykonuje swoje podania, jego obowiązki przejmuje wiceskip, którym zazwyczaj jest trzeci.
</p>
<p>
  Aby mieć pewność, iż zagranie zostanie odpowiednie wykonane, skip stoi w domu i wskazuje zawodnikowi swojej drużyny odpowiednie miejsce, z uwzględnieniem zakrzywienia toru rzutu. W tym czasie pozostali dwaj gracze mają za zadanie szczotkować lód przed kamieniem. Od chwili, w której kamień zostaje wypuszczony, żaden z zawodników nie ma prawa go dotknąć, tak więc szczotkowanie jest jedyną możliwością skorygowania jego toru jazdy.
</p>
</div>

<div class="article">
  <h1>Cel gry</h1>
  <p>
  Podstawowym celem gry jest zdobycie jak największej liczby punktów w każdym endzie. Uzyskuje się je przez umieszczenie własnych kamieni jak najbliżej środka domu i utrudnienie przeciwnikowi ich wybicia, przy jednoczesnych próbach wybijania kamieni drużyny przeciwnej. Ze względu na liczbę kamieni biorących udział w grze, maksymalnie w jednej rundzie można zdobyć osiem punktów. Takie sytuacje zdarzają się bardzo rzadko, ponieważ pod uwagę brane są tylko te położone w środku domu, ale nie dalej niż pierwszy kamień drużyny przeciwnej.
</p>
</div>

<div class="article">
  <h1>Zasada strefy wolnych strażników</h1>
  <%= image_tag('tor_opisy.png', size: "340x440", alt: "tor curlingowy - opisy linii") %>
  <p>
  Kamień, który zatrzymał się na obszarze pomiędzy Tee line, a Hog line, z wyłączeniem domu, jest uważany za strażnika. Jeżeli jeden z pierwszych czterech zagrywanych kamieni spowoduje usunięcie z gry strażnika przeciwnej drużyny, to zagrywany kamień jest usuwany z gry, a przesunięte kamienie są przywracane na swoje poprzednie pozycje.
</p>
</div>

<div class="article">
<h2>Pełne zasady gry w curling:</h2>
<a href="http://www.pzc.org.pl/pub/zasady%20curlingu.pdf"><strong>Polska wersja - skrócona</strong> </a><br>
<a href="http://www.worldcurling.org/rules-and-regulations"><strong>Angielska wersja - pełna</strong> </a><br>

</div>
</div>

curl/project/app/views/words/_form.html.erb
<div class="main">
  <span href="#" class="button" id="toggle-login"><h1>Dodaj słowo do słownika</h1></span>


  <%= form_for(@word) do |f| %>
      <% if @word.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

            <ul>
              <% @word.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

            <h3>Słowo:</h3>
            <%= f.text_field :name %><br>
            <h4>Jeżeli chcesz otrzymać powiadomienie o dodaniu tłumaczenia do tego słowa, zostaw nam e-mail.<h4>
              <h3>E-mail:</h3>
            <%= f.text_field :mail %><br>
<br>
        <%= f.submit "Dodaj!" %>

      </div>
  <% end %>

curl/project/app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

curl/project/app/views/words/index.html.erb
<div class="main">
  <h1>Słownik terminów curlingowych</h1>

    <h3>Wyszukaj słowo:</h3>
    <%= form_for search_path, method: :get do |f| %>
        <p>
          <%= text_field_tag :q, params[:q] %>
          <%= submit_tag "Szukaj!", name: nil %>
        </p>
    <% end %>
<div class="slowa">
      <% @words.each do |word| %>
          <% if word.displayed = true %>

                <p><strong><%= word.name %></strong>
                <%= word.translation %></p>

          <% end %>
      <% end %>
</div>
<p><%= link_to "Kategorie", categories_path %></p>
<p>Brakuje słowa? <%= link_to "Dodaj", new_word_path %></p>
</div>

curl/project/app/views/words/new.html.erb
<div class="main">
	

<%= render 'form' %>

<%= link_to 'Wróć do słownika', words_path %>

</div>

curl/project/app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main">
	<h1>Zapisano słowo</h1>
<h2><%= @word.name %></h2>

<p>
  <strong>Twój email:</strong>
  <%= @word.mail %>
</p>

<%= link_to 'Wszystkie słowa', words_path %>

</div>